### ISSUE TITLE
.lehrerKrank(): AttributeError: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by annhilati** [annhilati/vpmobil-py#9]
Traceback (most recent call last):
  File "c:\Users\antbe\.github\vpmobil-py\tests\app.py", line 10, in <module>
    print(vertretungsplan.fetch(20240618).lehrerKrank())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\antbe\AppData\Local\Programs\Python\Python312\Lib\site-packages\vpmobil\VpDay.py", line 97, in lehrerKrank
    for sr in std.find("Le").text.split(" "):
              ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by Joshi1531** [comment]
Es gab ein Problem mit dem bekommen der Kursnummer, da eine Klasse an diesem Tag auf Exkursion war und diese Stunde keine Kursnummer hatte. Das Problem ist behoben, die Funktion klappt nun einwandfrei.

**Comment by annhilati** [comment]
Zu früh gefreut...

Traceback (most recent call last):
  File "c:\Users\antbe\.github\vpmobil-py\tests\app.py", line 18, in <module>
    print(vertretungsplan.fetch(20240613).lehrerKrank())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\antbe\AppData\Local\Programs\Python\Python312\Lib\site-packages\vpmobil\VpDay.py", line 103, in lehrerKrank
    for sr in std.lehrer.split(" "):
              ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by Joshi1531** [comment]
Vorerst behoben, es kann nun keine Fehler mehr geben, da nun fast alles in einem try-Block ist. Wenn es Probleme wegen falschen Informationen gibt, kann man nochmal drüberschauen.
